version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: toei_test
          MYSQL_USER: root
          MYSQL_ROOT_HOST: "%"
    working_directory: ~/repo
    steps:
      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install pdo_mysql
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: sudo apt install mysql-client
      - run: mysql -h 127.0.0.1 -u root toei_test -e "create table users (id int, name text, created datetime, deleted datetime)"
      - run: mysql -h 127.0.0.1 -u root toei_test -e "create table messages (sender int, receiver int, body text, created datetime)"
      - run: ./vendor/bin/phpunit
